version: '2.1'

services:

  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
    - 8081:8080

  postgres:
    image: postgres:10.4-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ../bb-data:/var/lib/postgresql/data
    healthcheck:
      test: psql -U postgres -l
      interval: 10s
      retries: 5
    ports:
    - 5432:5432

  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
    - 5050:80

  adminer:
    image: adminer
    restart: always
    ports:
    - 8082:8080

  app:
    build: app
    ports:
    - 8083:5000

#  caddy:
#    image: abiosoft/caddy:0.11.0
#    depends_on:
#      app:
#        condition: service_started
#    volumes:
#      - './Caddyfile:/etc/Caddyfile'
#    ports:
#      - '80:80'
#      - '443:443'